[workspace]
members = [
    "core", 
    "cli", 
    "ks_std"
]

resolver = "3"
default-members = ["cli"]

[workspace.dependencies]
core = { path = "core" }

[workspace.package]
version = "0.5.0"
authors = ["Kyryl Lebedenko"]